services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: laravel-react-app
    container_name: laravel-react-app
    restart: always
    ports:
      - "8085:80"
      - "3000:3000"
    volumes:
      - ./laravel:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2
    networks:
      - laravel-react-net

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: python-app
    container_name: python
    restart: always
    working_dir: /app
    volumes:
      - ./python:/app
    networks:
      - laravel-react-net
    tty: true

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=book_db
      - MYSQL_USER=book_user
      - MYSQL_PASSWORD=passwd
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - laravel-react-net    

  solr:
    image: solr:9 # version9からベクトル検索がサポートされた
    container_name: solr
    restart: always
    ports:
      - "8983:8983"
    volumes:
      - ./solr:/var/solr
    command: 
      - solr-precreate
      - books
    networks:
      - laravel-react-net

volumes:
  db-volume:
  postgres-volume:

networks:
  laravel-react-net:
    driver: bridge
