services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    image: laravel-react-app
    container_name: laravel-react-app
    ports:
      - "8085:80"
      - "8086:8086"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_LOG_DIR=/var/log/apache2
    networks:
      - laravel-react-net

  python:
    image: python:3.12
    container_name: python
    restart: always
    volumes:
      - ./python:/var/www/html
    networks:
      - laravel-react-net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    volumes:
      - db-volume:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=book_db
      - MYSQL_USER=book_user
      - MYSQL_PASSWORD=passwd
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - laravel-react-net    

volumes:
  db-volume:
  postgres-volume:

networks:
  laravel-react-net:
    driver: bridge
